# =============================================================================
# Perfil: dev (ambiente de desarrollo compartido en AWS)
# =============================================================================

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

logging:
  level:
    com.truckdar.notifications: INFO
    org.springframework.security: INFO
